<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>responsible_primary_insurance</name>
   <tag></tag>
   <elementGuidId>aafcf1ad-1c3c-4cad-864a-71416fba7ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='responsible_primary_insurance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='responsible_primary_insurance']</value>
   </webElementProperties>
</WebElementEntity>
