<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>responsible_secondary_insurance</name>
   <tag></tag>
   <elementGuidId>3544128a-fb30-484a-a948-5fdd19d94cf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='responsible_secondary_insurance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='responsible_secondary_insurance']</value>
   </webElementProperties>
</WebElementEntity>
