<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_state</name>
   <tag></tag>
   <elementGuidId>dc98ce5a-8297-4026-a592-92c74b136f5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[contains(.,'Arkansas')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//option[contains(.,'Arkansas')]</value>
   </webElementProperties>
</WebElementEntity>
