<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_gender</name>
   <tag></tag>
   <elementGuidId>c4f94a65-472f-4d17-ab91-251b31c9bf3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//option[@value=&quot;Female&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//option[@value=&quot;Female&quot;]</value>
   </webElementProperties>
</WebElementEntity>
